version: '3'

services: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    volumes: 
      - ./:/var/www/html
    ports: 
      - ${NEXT_PORT}:${NEXT_PORT}
    tty: true
    restart: always
    networks: 
      - app

networks: 
  app:
    driver: bridge